name: Fishchantments
main: fun.sunrisemc.fishchants.Plugin
version: 0.0.5
api-version: 1.15
authors: ["TheFishNextDoor"]
description: Custom Enchantments by TheFishNextDoor
commands:
  fenchant:
    description: Apply a fishchantment
    usage: /fenchant <fishchantment> [level]
    permission: fishchantments.enchant
    aliases: [fishenchant, fishchantment]