name: Fishchantments
main: fun.sunrisemc.fishchantments.Plugin
version: 0.2.0
api-version: 1.15
authors: ["TheFishNextDoor"]
description: Custom Enchantments by TheFishNextDoor
commands:
  fenchant:
    description: Apply a fishchantment
    usage: /fenchant <fishchantment> [level]
    permission: fishchantments.enchant
    aliases: [fishenchant, fishchantment]