mobs-drop-books: true # Mobs will have a chance to drop books with custom enchantments
remove-overridden-enchantments: true # Remove unbreaking and mending when unbreakable is applied to an item
check-lore: true # Fixes plugins with lossy item saving from losing the applied enchantments (e.g. Essentials kits)
use-arabic-numerals: false # Use 1, 2, 3 instead of I, II, III
play-effects: true # Certain enchantments will create particle effects
disenchant-cost-levels: 3 # The number of levels it costs to use the disenchant command
combine-enchantments-cost-levels: 3 # The number of levels it costs to use the combine enchantments command
seeking-radius: 12 # How far away the seeking enchantment will look for entities