name: FishsCustomEnchantments
main: com.thefishnextdoor.customenchantments.Plugin
version: 0.3.3
api-version: 1.15
authors: ["TheFishNextDoor"]
description: Custom Enchantments by TheFishNextDoor
commands:
  fce:
    description: Custom Enchantments by TheFishNextDoor
    usage: /fce <subcommand>
  fenchant:
    description: Apply an enchantment to the item in your hand
    usage: /fenchant <enchantment> [level]
    permission: fce.admin.fenchant
  enchantinfo:
    description: Get information about an enchantment
    usage: /enchantinfo <enchantment>
    permission: fce.user.enchantinfo
  disenchant:
    description: Remove an enchantment from the item in your hand and return the enchantment book
    usage: /disenchant <enchantment>
    permission: fce.user.disenchant
permissions:
  fce.admin.reload:
    description: Allows the use of the reload command
  fce.admin.fenchant:
    description: Allows the use of the fenchant command
  fce.user.enchantinfo:
    description: Allows the use of the enchantinfo command
    default: true
  fce.user.disenchant:
    description: Allows the use of the disenchant command