name: FishsCustomEnchantments
main: com.thefishnextdoor.customenchantments.Plugin
version: 1.0.0
api-version: 1.15
authors: ["TheFishNextDoor"]
description: Custom Enchantments by TheFishNextDoor
commands:
  fce:
    description: Custom Enchantments by TheFishNextDoor.
    usage: /fce <subcommand>
  fenchant:
    description: Apply an enchantment to the item in your hand.
    usage: /fenchant <enchantment> [level]
    permission: fce.admin.fenchant
  enchantedbook:
    description: Get an enchanted book with the specified enchantment.
    usage: /enchantedbook <enchantment> [level]
    permission: fce.admin.enchantedbook
  enchantinfo:
    description: Get information about an enchantment.
    usage: /enchantinfo <enchantment>
    permission: fce.user.enchantinfo
  disenchant:
    description: Remove an enchantment from the item in your hand and return the enchantment book.
    usage: /disenchant <enchantment>
    permission: fce.user.disenchant
  combineenchantments:
    description: Combines the item in your main hand with the item in the slot to the right of it. Allows for combining custom enchantments on bedrock edition.
    usage: /combineenchantments
    permission: fce.user.combineenchantments
permissions:
  fce.admin.reload:
    description: Allows the use of the reload command
  fce.admin.fenchant:
    description: Allows the use of the fenchant command
  fce.admin.enchantedbook:
    description: Allows the use of the enchantedbook command
  fce.user.enchantinfo:
    description: Allows the use of the enchantinfo command
    default: true
  fce.user.disenchant:
    description: Allows the use of the disenchant command
  fce.user.combineenchantments:
    description: Allows the use of the combineenchantments command